djvideo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('youtube.urls'))
]

youtube/urls.py
from django.urls import path
from . import views
app_name='ytyoutube'
urlpatterns = [
    path('',views.youtube, name='youtube'),
    path('download/',views.download, name='download'),
    path('download/<resolution>/',views.yt_download, name='yt_downloaddone'),
]

youtube/models.py
from django.db import models

# Create your models here.

youtube/views.py
from django.shortcuts import render
from pytube import YouTube
import os

# Create your views here.

def youtube (request):
    return render(request, 'youtube/home.html')
def download (request):
    global url
    url = request.GET.get('ytlink')
    yt = YouTube(url)
    videos= []
    videos= yt.streams.filter(progressive=True).all()
    embed_link = url.replace("watch?v=","embed/")
    Title = yt.title
    context = {'videos':videos, 'embed':embed_link,'title':Title}

    return render(request, 'youtube/download.html', context)
def yt_download(request, resolution):
    global url
    homedir = os.path.expanduser("~")
    dir= homedir = 'Downloads'
    print(dir)
    if request.method =='POST':
        YouTube(url).streams.get_by_resolution(resolution).download(dir)
        
        
        return render(request, 'youtube/done.html')
    else:
        return render(request, 'youtube/error.html')



   

youtube/templates/youtube/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'youtube/css/home.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>{% block title %}{% endblock title %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand ms-5" href="/">
          <img src="/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="40" height="30">
          Youtube
          
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto me-5 mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              
          </div>
        </div>
      </nav>

{% block body %}{% endblock body %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    
  </body>
</html>

youtube/templates/youtube/done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Download done</h1>
    
</body>
</html>

youtube/templates/youtube/download.html
{% extends 'youtube/base.html' %}
{% block body %}


  <div class="row justify-content-center align-items-center h-100">
        <div class="col col-sm-6 col-md-6 col-xl-6 col-lg-3 mt-5 ">
           
        <h1>Title :{{title}}</h1>
<div class="embed-responsive embed-responsive-21by9">
  <iframe class="embed-responsive-item" src="{{embed}}" allowfullscreen></iframe>
</div>
<div>
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">Size</th>
        <th scope="col">Type</th>
        <th scope="col">Quality</th>
        <th scope="col">Download</th>
      </tr>
    </thead>
    {% for aav in videos %}
    <tbody>
      <tr>
        <th >{{aav.filesize}}</th>
        <td>{{aav.type}}</td>
        <td>{{aav.resolution}}</td>
        <td>
          <form action="{% url 'ytyoutube:yt_downloaddone' aav.resolution %}" method="post">
            {%csrf_token%}
            <button type="submit" class="btn btn-dark ">Download</button>
          </form>
        
        </td>
      </tr>
     
    </tbody>
    {% endfor %}
  </table>
</div>


    </div>

{% endblock body %}

youtube/templates/youtube/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Something wroung</h1>
</body>
</html>

youtube/templates/youtube/home.html
{% extends 'youtube/base.html' %}

{% block body %}

<div class="container-fluid">
    
      
    <div class="row justify-content-center align-items-center h-100">
        <div class="col col-sm-6 col-md-6 col-xl-6 col-lg-3 mt-5 ">
                <center><h1 class="m-3 lan">Youtube Video Downloader</h1></center>
            <form action="download/" method="GET">
                <div class="form-group">
                
                  <input type="text" name="ytlink"  id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter link">
                  
                </div>
               
               <center> <button type="submit" class=" mt-4 btn btn-dark btn-lg btn-block">Submit</button></center>
              </form>

        </div>
        

    </div>

    

</div>

{% endblock body %}